---
# System Configuration Role - EC2 기본 설정

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: Set timezone to Asia/Seoul
  timezone:
    name: Asia/Seoul
  become: yes

- name: Set friendly hostname
  hostname:
    name: likelion-dev-server
  become: yes

- name: Update /etc/hosts with new hostname
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.0\.1.*localhost'
    line: '127.0.0.1 localhost likelion-dev-server'
    backup: yes
  become: yes

- name: Configure swap memory
  include_tasks: swap.yml

# SSH tunnel setup moved to post_tasks in main playbook to ensure variables are loaded