---
# Swap memory 설정

- name: Check if swap file exists
  stat:
    path: /swapfile
  register: swap_file_check

- name: Create swap file
  command: fallocate -l 2G /swapfile
  become: yes
  when: not swap_file_check.stat.exists

- name: Set swap file permissions
  file:
    path: /swapfile
    mode: '0600'
  become: yes

- name: Make swap file
  command: mkswap /swapfile
  become: yes
  when: not swap_file_check.stat.exists

- name: Enable swap file
  command: swapon /swapfile
  become: yes
  when: not swap_file_check.stat.exists

- name: Add swap to fstab
  lineinfile:
    path: /etc/fstab
    line: '/swapfile none swap sw 0 0'
    state: present
  become: yes

- name: Set swappiness
  sysctl:
    name: vm.swappiness
    value: '10'
    state: present
    sysctl_file: /etc/sysctl.conf
  become: yes

- name: Set vfs_cache_pressure
  sysctl:
    name: vm.vfs_cache_pressure
    value: '50'
    state: present
    sysctl_file: /etc/sysctl.conf
  become: yes