---
# Install and configure nginx

- name: Install nginx
  apt:
    name: nginx
    state: present
  become: yes

- name: Start and enable nginx
  systemd:
    name: nginx
    state: started
    enabled: yes
  become: yes

- name: Remove default nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  become: yes
  notify: restart nginx

- name: Create nginx configuration directory structure
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop:
    - /etc/nginx/sites-available
    - /etc/nginx/sites-enabled
    - /etc/nginx/conf.d
  become: yes

- name: Create basic nginx configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
    backup: yes
  become: yes
  notify: restart nginx

- name: Create default application nginx config
  template:
    src: app.conf.j2
    dest: /etc/nginx/sites-available/app
    owner: root
    group: root
    mode: '0644'
  become: yes

- name: Enable application site
  file:
    src: /etc/nginx/sites-available/app
    dest: /etc/nginx/sites-enabled/app
    state: link
  become: yes
  notify: restart nginx